name: coffee_escapades
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  glassmorphism: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3


flutter:

  uses-material-design: true

  fonts:
      - family: Orbitron
        fonts:
          - asset: assets/fonts/orbitron/Orbitron-Regular.ttf
            weight: 300
          - asset: assets/fonts/orbitron/Orbitron-Medium.ttf
            weight: 400
          - asset: assets/fonts/orbitron/Orbitron-SemiBold.ttf
            weight: 500
          - asset: assets/fonts/orbitron/Orbitron-Bold.ttf
            weight: 600
          - asset: assets/fonts/orbitron/Orbitron-ExtraBold.ttf
            weight: 700
          - asset: assets/fonts/orbitron/Orbitron-Black.ttf
            weight: 800
      - family: Chakra Petch
        fonts:
          - asset: assets/fonts/ChakraPetch/ChakraPetch-Regular.ttf
            weight: 200
          - asset: assets/fonts/ChakraPetch/ChakraPetch-Medium.ttf
            weight: 400
          - asset: assets/fonts/ChakraPetch/ChakraPetch-SemiBold.ttf
            weight: 500
          - asset: assets/fonts/ChakraPetch/ChakraPetch-Bold.ttf
            weight: 600
      - family: Qualion
        fonts:
          - asset: assets/fonts/qualion/Qualion-Thin.ttf
            weight: 200
          - asset: assets/fonts/qualion/Qualion-Regular.ttf
            weight: 300
          - asset: assets/fonts/qualion/Qualion-Book.ttf
            weight: 400
   
  assets:
    - assets/images/flags/
    - assets/images/fullstack/
    - assets/images/tools/
    - assets/images/company/
    - assets/images/hobbies/
    - assets/images/




